### ISSUE TITLE
No tracks at all

### ISSUE THREAD

**Issue by owcv** [interfasys/piwik-yourls#4]
I've installed the plugin as described in the ReadMe, but my Piwik doesn't track any hits at all. Am I doing something wrong or is this just deprecated?

**Comment by keverw** [comment]
Not tracking at all for me either. As far as I know I installed it correctly. I think maybe it's needing a update and older.

**Comment by pvogensen** [comment]
I can see this is from last year:-) However, I have just tried to install the plugin and am having the same problem -no tracking. I am using yourls 1.7. Has anyone found a solution to this?

**Comment by 3rdLOF** [comment]
Not working neither. Labeling it as "abandoned".

**Comment by oparoz** [comment]
Hello all,
I should be able to take a look at this next week. Hopefully, it's just a mater of changing the name of a few methods.
Do you get any PHP errors at all?

**Comment by oparoz** [comment]
I've created the dev branch for Yourls 1.7+. Let me know if you still encounter issues.
